import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  Image,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";
import type {
  BusinessPlanBasics,
  BrandNameSuggestion,
  DevilsAdvocate,
  ValidationRoadmap,
  MenuOrProductData,
  MarketingPlan,
} from "@/types/deep-dive";

const s = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", fontSize: 10 },
  title: { fontSize: 24, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  subtitle: { fontSize: 12, color: "#666", marginBottom: 6 },
  sectionTitle: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    marginTop: 16,
    marginBottom: 8,
    paddingBottom: 4,
    borderBottom: "1 solid #e5e5e5",
  },
  subTitle: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    marginTop: 10,
    marginBottom: 4,
  },
  row: { flexDirection: "row", marginBottom: 4 },
  label: { width: 140, color: "#666" },
  value: { flex: 1, fontFamily: "Helvetica-Bold" },
  bullet: { marginBottom: 3, paddingLeft: 12 },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f5f5f5",
    padding: 6,
    fontFamily: "Helvetica-Bold",
    fontSize: 9,
  },
  tableRow: {
    flexDirection: "row",
    padding: 6,
    borderBottom: "0.5 solid #e5e5e5",
    fontSize: 9,
  },
  card: {
    border: "1 solid #e5e5e5",
    borderRadius: 4,
    padding: 10,
    marginBottom: 8,
  },
  badge: {
    fontSize: 8,
    backgroundColor: "#f0f0f0",
    borderRadius: 3,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 8,
    color: "#999",
  },
});

interface DeepDivePDFData {
  ideaTitle: string;
  category: string;
  location: string;
  businessPlan: BusinessPlanBasics | null;
  brandNames: BrandNameSuggestion[] | null;
  devilsAdvocate: DevilsAdvocate | null;
  validationRoadmap: ValidationRoadmap | null;
  menuOrProduct: MenuOrProductData | null;
  marketingPlan: MarketingPlan | null;
  moodboardImages: string[] | null;
  logoUrl: string | null;
}

function DeepDiveReport({ data }: { data: DeepDivePDFData }) {
  const bp = data.businessPlan;
  const da = data.devilsAdvocate;
  const vr = data.validationRoadmap;
  const mop = data.menuOrProduct;
  const mp = data.marketingPlan;

  return (
    <Document>
      {/* Title Page */}
      <Page size="A4" style={s.page}>
        <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
          <Text style={{ fontSize: 32, fontFamily: "Helvetica-Bold", marginBottom: 8 }}>
            Deep Dive Report
          </Text>
          <Text style={{ fontSize: 18, marginBottom: 20 }}>{data.ideaTitle}</Text>
          <Text style={{ fontSize: 12, color: "#666" }}>
            {data.category} — {data.location}
          </Text>
          <Text style={{ fontSize: 10, color: "#999", marginTop: 8 }}>
            Generated on {new Date().toLocaleDateString()}
          </Text>
        </View>
        <Text style={s.footer}>
          Generated by FoodLaunch • Deep Dive Report
        </Text>
      </Page>

      {/* Business Plan */}
      {bp && (
        <Page size="A4" style={s.page}>
          <Text style={s.sectionTitle}>Business Plan</Text>

          <Text style={s.subTitle}>Executive Summary</Text>
          <Text style={{ marginBottom: 6 }}>{bp.executive_summary.overview}</Text>
          <View style={s.row}>
            <Text style={s.label}>Value Proposition:</Text>
            <Text style={{ flex: 1 }}>{bp.executive_summary.value_proposition}</Text>
          </View>
          <View style={s.row}>
            <Text style={s.label}>Business Model:</Text>
            <Text style={{ flex: 1 }}>{bp.executive_summary.business_model}</Text>
          </View>

          <Text style={s.subTitle}>Mission & Vision</Text>
          <View style={s.row}>
            <Text style={s.label}>Mission:</Text>
            <Text style={{ flex: 1 }}>{bp.mission_vision.mission}</Text>
          </View>
          <View style={s.row}>
            <Text style={s.label}>Vision:</Text>
            <Text style={{ flex: 1 }}>{bp.mission_vision.vision}</Text>
          </View>

          <Text style={s.subTitle}>Target Market</Text>
          <View style={s.row}>
            <Text style={s.label}>Primary Segment:</Text>
            <Text style={{ flex: 1 }}>{bp.target_market.primary_segment}</Text>
          </View>
          <View style={s.row}>
            <Text style={s.label}>Segment Size:</Text>
            <Text style={s.value}>{bp.target_market.segment_size}</Text>
          </View>
          <Text style={{ ...s.subTitle, fontSize: 10 }}>Pain Points:</Text>
          {bp.target_market.pain_points.map((p, i) => (
            <Text key={i} style={s.bullet}>• {p}</Text>
          ))}

          <Text style={s.subTitle}>Competitive Advantage</Text>
          {bp.competitive_advantage.your_differentiators.map((d, i) => (
            <Text key={i} style={s.bullet}>• {d}</Text>
          ))}
          <View style={s.row}>
            <Text style={s.label}>Moat Strategy:</Text>
            <Text style={{ flex: 1 }}>{bp.competitive_advantage.moat_strategy}</Text>
          </View>

          <Text style={s.footer}>
            Generated by FoodLaunch • Deep Dive Report
          </Text>
        </Page>
      )}

      {/* Financial Projections */}
      {bp && (
        <Page size="A4" style={s.page}>
          <Text style={s.sectionTitle}>Financial Projections</Text>

          <View style={s.row}>
            <Text style={s.label}>Break-Even:</Text>
            <Text style={s.value}>{bp.financial_projections.break_even_timeline}</Text>
          </View>
          <View style={s.row}>
            <Text style={s.label}>Funding Needed:</Text>
            <Text style={s.value}>{bp.financial_projections.funding_needed}</Text>
          </View>

          <Text style={s.subTitle}>Startup Costs</Text>
          <View style={s.tableHeader}>
            <Text style={{ width: "60%" }}>Item</Text>
            <Text style={{ width: "40%", textAlign: "right" }}>Amount</Text>
          </View>
          {bp.financial_projections.startup_costs.map((c, i) => (
            <View key={i} style={s.tableRow}>
              <Text style={{ width: "60%" }}>{c.item}</Text>
              <Text style={{ width: "40%", textAlign: "right" }}>{c.amount}</Text>
            </View>
          ))}

          <Text style={s.subTitle}>Revenue Projections</Text>
          <View style={s.tableHeader}>
            <Text style={{ width: "15%" }}>Month</Text>
            <Text style={{ width: "25%", textAlign: "right" }}>Revenue</Text>
            <Text style={{ width: "60%", paddingLeft: 8 }}>Notes</Text>
          </View>
          {bp.financial_projections.revenue_projections.map((r, i) => (
            <View key={i} style={s.tableRow}>
              <Text style={{ width: "15%" }}>{r.month}</Text>
              <Text style={{ width: "25%", textAlign: "right" }}>{r.revenue}</Text>
              <Text style={{ width: "60%", paddingLeft: 8, color: "#666" }}>{r.notes}</Text>
            </View>
          ))}

          <Text style={s.footer}>
            Generated by FoodLaunch • Deep Dive Report
          </Text>
        </Page>
      )}

      {/* Brand Names */}
      {data.brandNames && data.brandNames.length > 0 && (
        <Page size="A4" style={s.page}>
          <Text style={s.sectionTitle}>Potential Brand Names</Text>
          {data.brandNames.map((name, i) => (
            <View key={i} style={s.card}>
              <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 13, marginBottom: 2 }}>
                {name.name}
              </Text>
              <Text style={{ color: "#666", fontStyle: "italic", marginBottom: 4, fontSize: 9 }}>
                &ldquo;{name.tagline}&rdquo;
              </Text>
              <Text style={{ marginBottom: 2 }}>{name.reasoning}</Text>
              <Text style={{ color: "#666", fontSize: 9 }}>{name.domain_suggestion}</Text>
            </View>
          ))}
          <Text style={s.footer}>
            Generated by FoodLaunch • Deep Dive Report
          </Text>
        </Page>
      )}

      {/* Menu Engineering / Product Lineup */}
      {mop && mop.type === "menu" && (
        <Page size="A4" style={s.page}>
          <Text style={s.sectionTitle}>Menu Engineering</Text>

          <View style={s.row}>
            <Text style={s.label}>Avg Food Cost:</Text>
            <Text style={s.value}>{mop.data.food_cost_summary.average_food_cost_percent}%</Text>
          </View>
          <View style={s.row}>
            <Text style={s.label}>Target Food Cost:</Text>
            <Text style={s.value}>{mop.data.food_cost_summary.target_food_cost_percent}%</Text>
          </View>

          {mop.data.menu_categories.map((cat, ci) => (
            <View key={ci}>
              <Text style={s.subTitle}>{cat.name}</Text>
              <View style={s.tableHeader}>
                <Text style={{ width: "30%" }}>Item</Text>
                <Text style={{ width: "15%", textAlign: "right" }}>Price</Text>
                <Text style={{ width: "15%", textAlign: "center" }}>Cost %</Text>
                <Text style={{ width: "15%", textAlign: "center" }}>Margin %</Text>
                <Text style={{ width: "25%", textAlign: "center" }}>Type</Text>
              </View>
              {cat.items.map((item, ii) => (
                <View key={ii} style={s.tableRow}>
                  <Text style={{ width: "30%" }}>{item.name}</Text>
                  <Text style={{ width: "15%", textAlign: "right" }}>{item.price}</Text>
                  <Text style={{ width: "15%", textAlign: "center" }}>{item.food_cost_percent}%</Text>
                  <Text style={{ width: "15%", textAlign: "center" }}>{item.profit_margin_percent}%</Text>
                  <Text style={{ width: "25%", textAlign: "center" }}>{item.classification}</Text>
                </View>
              ))}
            </View>
          ))}

          <Text style={s.subTitle}>Pricing Strategy</Text>
          <Text style={{ marginBottom: 6 }}>{mop.data.pricing_strategy}</Text>

          {mop.data.combo_strategies.length > 0 && (
            <View>
              <Text style={s.subTitle}>Combo Strategies</Text>
              {mop.data.combo_strategies.map((combo, i) => (
                <View key={i} style={s.card}>
                  <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 10 }}>
                    {combo.name} — {combo.bundle_price} (save {combo.savings_percent}%)
                  </Text>
                  <Text style={{ fontSize: 9, color: "#666" }}>{combo.items.join(" + ")}</Text>
                </View>
              ))}
            </View>
          )}

          <Text style={s.footer}>
            Generated by FoodLaunch • Deep Dive Report
          </Text>
        </Page>
      )}

      {mop && mop.type === "product_lineup" && (
        <Page size="A4" style={s.page}>
          <Text style={s.sectionTitle}>Product Lineup</Text>

          <View style={s.row}>
            <Text style={s.label}>Avg Margin:</Text>
            <Text style={s.value}>{mop.data.margin_summary.average_margin_percent}%</Text>
          </View>
          <View style={s.row}>
            <Text style={s.label}>Target Margin:</Text>
            <Text style={s.value}>{mop.data.margin_summary.target_margin_percent}%</Text>
          </View>

          <View style={s.tableHeader}>
            <Text style={{ width: "25%" }}>Product</Text>
            <Text style={{ width: "15%", textAlign: "right" }}>Price</Text>
            <Text style={{ width: "15%", textAlign: "right" }}>Cost</Text>
            <Text style={{ width: "15%", textAlign: "center" }}>Margin %</Text>
            <Text style={{ width: "30%", textAlign: "center" }}>Type</Text>
          </View>
          {mop.data.products.map((p, i) => (
            <View key={i} style={s.tableRow}>
              <Text style={{ width: "25%" }}>{p.name}</Text>
              <Text style={{ width: "15%", textAlign: "right" }}>{p.price}</Text>
              <Text style={{ width: "15%", textAlign: "right" }}>{p.cost_to_produce}</Text>
              <Text style={{ width: "15%", textAlign: "center" }}>{p.margin_percent}%</Text>
              <Text style={{ width: "30%", textAlign: "center" }}>{p.classification}</Text>
            </View>
          ))}

          <Text style={s.subTitle}>Pricing Strategy</Text>
          <Text style={{ marginBottom: 6 }}>{mop.data.pricing_strategy}</Text>

          <Text style={s.subTitle}>Distribution Channels</Text>
          {mop.data.distribution_channels.map((ch, i) => (
            <Text key={i} style={s.bullet}>• {ch}</Text>
          ))}

          <Text style={s.subTitle}>Product Roadmap</Text>
          <Text>{mop.data.product_roadmap}</Text>

          <Text style={s.footer}>
            Generated by FoodLaunch • Deep Dive Report
          </Text>
        </Page>
      )}

      {/* Marketing Plan */}
      {mp && (
        <Page size="A4" style={s.page}>
          <Text style={s.sectionTitle}>90-Day Marketing Plan</Text>

          <View style={s.row}>
            <Text style={s.label}>Total Budget:</Text>
            <Text style={s.value}>{mp.total_budget}</Text>
          </View>
          <Text style={{ marginBottom: 8 }}>{mp.overview}</Text>

          <Text style={s.subTitle}>Marketing Channels</Text>
          <View style={s.tableHeader}>
            <Text style={{ width: "20%" }}>Channel</Text>
            <Text style={{ width: "10%", textAlign: "center" }}>Priority</Text>
            <Text style={{ width: "12%", textAlign: "right" }}>Budget %</Text>
            <Text style={{ width: "58%", paddingLeft: 8 }}>Strategy</Text>
          </View>
          {mp.channels.map((ch, i) => (
            <View key={i} style={s.tableRow}>
              <Text style={{ width: "20%" }}>{ch.channel}</Text>
              <Text style={{ width: "10%", textAlign: "center" }}>{ch.priority}</Text>
              <Text style={{ width: "12%", textAlign: "right" }}>{ch.budget_allocation_percent}%</Text>
              <Text style={{ width: "58%", paddingLeft: 8, color: "#444" }}>{ch.strategy}</Text>
            </View>
          ))}

          <Text style={s.subTitle}>Key Performance Indicators</Text>
          {mp.kpis.map((kpi, i) => (
            <View key={i} style={s.row}>
              <Text style={s.label}>{kpi.metric}:</Text>
              <Text style={s.value}>{kpi.target}</Text>
            </View>
          ))}

          <Text style={s.subTitle}>Content Calendar Themes</Text>
          {mp.content_calendar.map((week, i) => (
            <Text key={i} style={s.bullet}>
              • Week {week.week}: {week.theme}
            </Text>
          ))}

          <Text style={s.footer}>
            Generated by FoodLaunch • Deep Dive Report
          </Text>
        </Page>
      )}

      {/* Devil's Advocate */}
      {da && (
        <Page size="A4" style={s.page}>
          <Text style={s.sectionTitle}>Devil&apos;s Advocate</Text>

          <View style={{ ...s.card, backgroundColor: "#fff5f5", borderColor: "#fed7d7" }}>
            <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 9, marginBottom: 4 }}>
              Honest Assessment
            </Text>
            <Text>{da.honest_assessment}</Text>
          </View>

          <Text style={s.subTitle}>Critical Risks</Text>
          <View style={s.tableHeader}>
            <Text style={{ width: "35%" }}>Risk</Text>
            <Text style={{ width: "12%", textAlign: "center" }}>Severity</Text>
            <Text style={{ width: "12%", textAlign: "center" }}>Likelihood</Text>
            <Text style={{ width: "41%" }}>Mitigation</Text>
          </View>
          {da.critical_risks.map((r, i) => (
            <View key={i} style={s.tableRow}>
              <Text style={{ width: "35%" }}>{r.risk}</Text>
              <Text style={{ width: "12%", textAlign: "center" }}>{r.severity}</Text>
              <Text style={{ width: "12%", textAlign: "center" }}>{r.likelihood}</Text>
              <Text style={{ width: "41%" }}>{r.mitigation}</Text>
            </View>
          ))}

          <Text style={s.subTitle}>Failure Modes</Text>
          {da.failure_modes.map((fm, i) => (
            <View key={i} style={{ marginBottom: 6 }}>
              <Text style={{ fontFamily: "Helvetica-Bold", fontSize: 9 }}>{fm.scenario}</Text>
              <Text style={{ color: "#666" }}>Trigger: {fm.trigger}</Text>
              <Text style={{ color: "#2f855a" }}>Prevention: {fm.prevention}</Text>
            </View>
          ))}

          <Text style={s.footer}>
            Generated by FoodLaunch • Deep Dive Report
          </Text>
        </Page>
      )}

      {/* Validation Roadmap */}
      {vr && vr.phases.map((phase) => (
        <Page key={phase.phase} size="A4" style={s.page}>
          <Text style={s.sectionTitle}>
            Validation Roadmap — Phase {phase.phase}: {phase.name}
          </Text>

          {phase.steps.map((step) => (
            <View key={step.id} style={{ ...s.card, marginBottom: 6 }}>
              <View style={{ flexDirection: "row", justifyContent: "space-between", marginBottom: 4 }}>
                <Text style={{ fontFamily: "Helvetica-Bold" }}>{step.title}</Text>
                <Text style={{ fontSize: 8, color: "#666" }}>
                  Week {step.week} • {step.estimated_hours}h • {step.category}
                </Text>
              </View>
              <Text style={{ marginBottom: 4, color: "#444" }}>{step.description}</Text>
              {step.action_items.map((item, i) => (
                <Text key={i} style={s.bullet}>• {item}</Text>
              ))}
              <Text style={{ fontSize: 8, color: "#666", marginTop: 4 }}>
                Success: {step.success_criteria}
              </Text>
            </View>
          ))}

          <Text style={s.footer}>
            Generated by FoodLaunch • Deep Dive Report
          </Text>
        </Page>
      ))}

      {/* Moodboard */}
      {(data.moodboardImages?.length || data.logoUrl) && (
        <Page size="A4" style={s.page}>
          <Text style={s.sectionTitle}>Moodboard & Logo</Text>

          {data.logoUrl && (
            <View style={{ alignItems: "center", marginBottom: 16 }}>
              <Text style={s.subTitle}>Logo</Text>
              <Image src={data.logoUrl} style={{ width: 150, height: 150 }} />
            </View>
          )}

          {data.moodboardImages && data.moodboardImages.length > 0 && (
            <View>
              <Text style={s.subTitle}>Brand Imagery</Text>
              <View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>
                {data.moodboardImages.map((url, i) => (
                  <Image
                    key={i}
                    src={url}
                    style={{ width: 240, height: 240, borderRadius: 4 }}
                  />
                ))}
              </View>
            </View>
          )}

          <Text style={s.footer}>
            Generated by FoodLaunch • Deep Dive Report
          </Text>
        </Page>
      )}
    </Document>
  );
}

export async function renderDeepDivePDF(deepDive: {
  ideaTitle: string;
  category: string;
  location: string;
  businessPlan: unknown;
  brandNames: unknown;
  devilsAdvocate: unknown;
  validationRoadmap: unknown;
  menuOrProduct: unknown;
  marketingPlan: unknown;
  moodboardImages: unknown;
  logoUrl: string | null;
}): Promise<Buffer> {
  return renderToBuffer(
    <DeepDiveReport
      data={{
        ideaTitle: deepDive.ideaTitle,
        category: deepDive.category,
        location: deepDive.location,
        businessPlan: deepDive.businessPlan as BusinessPlanBasics | null,
        brandNames: deepDive.brandNames as BrandNameSuggestion[] | null,
        devilsAdvocate: deepDive.devilsAdvocate as DevilsAdvocate | null,
        validationRoadmap: deepDive.validationRoadmap as ValidationRoadmap | null,
        menuOrProduct: deepDive.menuOrProduct as MenuOrProductData | null,
        marketingPlan: deepDive.marketingPlan as MarketingPlan | null,
        moodboardImages: deepDive.moodboardImages as string[] | null,
        logoUrl: deepDive.logoUrl,
      }}
    />
  );
}
