import { CATEGORIES, POPULAR_LOCATIONS } from "@/lib/constants";
import { hash, seededRange, pickRandom, generateId, randomDate } from "./helpers";
import type { LeaderboardIdea } from "@/types/leaderboard";

const IDEA_TEMPLATES: { title: string; oneLiner: string; keywords: string[] }[] = [
  // Restaurant & Dining
  { title: "Farm-to-Table Italian Trattoria", oneLiner: "Hyper-local Italian restaurant sourcing 90% of ingredients from farms within 50 miles", keywords: ["farm to table restaurant", "italian restaurant near me", "local farm dining"] },
  { title: "Plant-Based Fine Dining", oneLiner: "Upscale vegan tasting menu restaurant redefining plant-forward cuisine", keywords: ["vegan fine dining", "plant based restaurant", "upscale vegan food"] },
  { title: "Korean BBQ Fast-Casual", oneLiner: "Affordable Korean BBQ with individual tabletop grills and a build-your-own bowl option", keywords: ["korean bbq near me", "korean restaurant", "bibimbap bowl"] },
  { title: "Zero-Waste Restaurant", oneLiner: "Full-service restaurant with zero food waste — every byproduct repurposed or composted", keywords: ["zero waste restaurant", "sustainable dining", "eco friendly restaurant"] },
  { title: "AI-Personalized Menu Restaurant", oneLiner: "Diners scan a QR code, answer taste preferences, and get a personalized menu generated by AI", keywords: ["smart restaurant", "personalized dining", "ai menu"] },
  { title: "Breakfast-Only All-Day Diner", oneLiner: "Premium breakfast and brunch dishes served all day in a nostalgic diner atmosphere", keywords: ["breakfast restaurant", "brunch near me", "all day breakfast"] },
  { title: "Ethiopian Injera House", oneLiner: "Authentic Ethiopian communal dining with house-made injera and traditional stews", keywords: ["ethiopian restaurant near me", "injera restaurant", "african food"] },
  { title: "Ramen Lab & Noodle Bar", oneLiner: "Build-your-own ramen with rotating seasonal broths and fresh handmade noodles", keywords: ["ramen near me", "noodle bar", "best ramen"] },
  { title: "Mediterranean Seafood Grill", oneLiner: "Coastal Mediterranean cuisine featuring daily-caught sustainable seafood", keywords: ["seafood restaurant", "mediterranean food near me", "fresh fish restaurant"] },
  { title: "Peruvian Ceviche Bar", oneLiner: "Fresh ceviche and Peruvian street food in a vibrant, casual setting", keywords: ["ceviche near me", "peruvian restaurant", "peruvian food"] },

  // Food Truck & Street Food
  { title: "Gourmet Grilled Cheese Truck", oneLiner: "Elevated grilled cheese sandwiches with artisan bread and premium cheese blends", keywords: ["grilled cheese food truck", "gourmet sandwich", "food truck near me"] },
  { title: "Filipino Street Food Truck", oneLiner: "Authentic sisig, lumpia, and halo-halo bringing Filipino flavors to the streets", keywords: ["filipino food truck", "filipino food near me", "lumpia food truck"] },
  { title: "Vegan Taco Truck", oneLiner: "Plant-based Mexican street tacos with jackfruit carnitas and cashew crema", keywords: ["vegan tacos", "vegan food truck", "plant based mexican food"] },
  { title: "Lobster Roll Mobile Kitchen", oneLiner: "New England-style lobster rolls served from a coastal-themed food truck", keywords: ["lobster roll food truck", "seafood food truck", "lobster roll near me"] },
  { title: "Wood-Fired Pizza Truck", oneLiner: "Neapolitan-style pizzas baked in a mobile wood-fired oven in 90 seconds", keywords: ["pizza food truck", "wood fired pizza near me", "mobile pizza oven"] },
  { title: "Indian Chaat & Curry Truck", oneLiner: "Authentic Indian street snacks and quick-serve curry bowls from a food truck", keywords: ["indian food truck", "curry near me", "indian street food"] },
  { title: "Arepa & Empanada Truck", oneLiner: "Venezuelan and Colombian arepas and empanadas with traditional fillings", keywords: ["arepa food truck", "empanada near me", "latin food truck"] },
  { title: "BBQ Brisket Food Truck", oneLiner: "Low-and-slow smoked brisket, pulled pork, and craft BBQ sauces on wheels", keywords: ["bbq food truck", "smoked brisket near me", "barbecue food truck"] },

  // Bakery & Pastry
  { title: "Sourdough Micro-Bakery", oneLiner: "Small-batch sourdough bread and pastries baked fresh daily with heritage grains", keywords: ["sourdough bakery", "artisan bread near me", "fresh bread bakery"] },
  { title: "Japanese Milk Bread Bakery", oneLiner: "Fluffy shokupan and Japanese-style pastries with a modern twist", keywords: ["japanese bakery near me", "milk bread", "japanese pastry shop"] },
  { title: "Allergen-Free Bakery", oneLiner: "100% gluten-free, nut-free bakery specializing in celebration cakes and daily pastries", keywords: ["gluten free bakery", "allergen free cakes", "nut free bakery near me"] },
  { title: "French Viennoiserie Shop", oneLiner: "Authentic croissants, pain au chocolat, and French pastries made with imported butter", keywords: ["croissant bakery near me", "french bakery", "pain au chocolat"] },
  { title: "Custom Cookie Decorating Studio", oneLiner: "Decorated cookies for events plus walk-in DIY cookie decorating experiences", keywords: ["custom cookies", "cookie decorating", "decorated cookies near me"] },
  { title: "Bagel Shop with House-Made Cream Cheese", oneLiner: "New York-style hand-rolled bagels with creative flavored cream cheese spreads", keywords: ["bagel shop near me", "best bagels", "fresh bagels"] },

  // Catering & Events
  { title: "Corporate Lunch Catering Platform", oneLiner: "Daily rotating menus from local restaurants delivered to offices with zero-waste packaging", keywords: ["corporate catering", "office lunch delivery", "business catering service"] },
  { title: "Private Chef Experience Marketplace", oneLiner: "Book a private chef for dinner parties, date nights, or special occasions at home", keywords: ["private chef near me", "hire private chef", "dinner party catering"] },
  { title: "Wedding Taco Bar Catering", oneLiner: "Interactive taco stations for weddings and events with custom menus and dietary options", keywords: ["wedding catering", "taco bar catering", "event food service"] },
  { title: "Luxury Picnic Setup & Catering", oneLiner: "Instagram-worthy outdoor picnic setups with gourmet food in scenic locations", keywords: ["luxury picnic setup", "picnic catering", "outdoor dining experience"] },
  { title: "Cultural Feast Catering", oneLiner: "Authentic multi-course cultural dining experiences for corporate team-building events", keywords: ["cultural food experience", "team building dinner", "authentic cuisine catering"] },

  // Ghost Kitchen & Delivery-Only
  { title: "Multi-Brand Ghost Kitchen", oneLiner: "One kitchen, five delivery-only brands — each targeting a different cuisine and audience", keywords: ["ghost kitchen", "cloud kitchen", "virtual restaurant"] },
  { title: "Healthy Bowl Delivery Brand", oneLiner: "Poke, grain, and smoothie bowls optimized for delivery with no-spill packaging", keywords: ["poke bowl delivery", "healthy food delivery", "grain bowl near me"] },
  { title: "Late-Night Comfort Food Kitchen", oneLiner: "Delivery-only comfort food (burgers, mac & cheese, loaded fries) from 9PM to 3AM", keywords: ["late night food delivery", "midnight snack delivery", "comfort food delivery"] },
  { title: "Keto & Low-Carb Delivery Kitchen", oneLiner: "Delivery-only kitchen specializing in keto-friendly meals with macro tracking", keywords: ["keto meal delivery", "low carb food delivery", "keto restaurant near me"] },
  { title: "Baby & Toddler Meal Delivery", oneLiner: "Nutritionist-designed, organic baby food and toddler meals delivered fresh weekly", keywords: ["baby food delivery", "toddler meals delivery", "organic baby food"] },
  { title: "Protein-Packed Fitness Meals", oneLiner: "Ghost kitchen delivering high-protein, macro-balanced meals for gym-goers", keywords: ["meal prep delivery", "fitness meal delivery", "high protein meals near me"] },
  { title: "Virtual Ramen Brand", oneLiner: "Delivery-optimized ramen with separated broth and noodles for at-home assembly", keywords: ["ramen delivery", "virtual restaurant ramen", "ghost kitchen ramen"] },

  // Bar, Pub & Nightlife
  { title: "Craft Cocktail & Tapas Bar", oneLiner: "Seasonal craft cocktails paired with Spanish-inspired small plates in an intimate setting", keywords: ["cocktail bar near me", "tapas bar", "craft cocktails"] },
  { title: "Zero-Alcohol Bar", oneLiner: "Sophisticated non-alcoholic cocktail bar for sober-curious drinkers and designated drivers", keywords: ["non alcoholic bar", "sober bar", "mocktail bar near me"] },
  { title: "Speakeasy Wine Bar", oneLiner: "Hidden-entrance wine bar with curated natural wines and charcuterie boards", keywords: ["wine bar near me", "natural wine bar", "speakeasy bar"] },
  { title: "Craft Beer & Board Game Pub", oneLiner: "Local craft beer taproom with a library of 500+ board games and tabletop events", keywords: ["board game bar", "craft beer pub", "game night bar near me"] },
  { title: "Sake & Izakaya Bar", oneLiner: "Japanese-style izakaya with premium sake flights and authentic bar snacks", keywords: ["sake bar near me", "izakaya", "japanese bar food"] },

  // Café & Coffee Shop
  { title: "Specialty Coffee & Coworking Café", oneLiner: "Third-wave coffee shop with dedicated coworking space, fast WiFi, and meeting rooms", keywords: ["coffee shop coworking", "cafe with wifi near me", "coworking coffee shop"] },
  { title: "Matcha & Japanese Tea House", oneLiner: "Ceremonial-grade matcha lattes and Japanese teas in a minimalist zen setting", keywords: ["matcha cafe near me", "japanese tea house", "matcha latte"] },
  { title: "Cat Café", oneLiner: "Coffee shop with adoptable rescue cats — specialty drinks and a cozy feline lounge", keywords: ["cat cafe near me", "cat coffee shop", "animal cafe"] },
  { title: "Micro-Roastery Coffee Shop", oneLiner: "Roast beans in-house, serve single-origin pour-overs, and sell bags direct to consumer", keywords: ["specialty coffee near me", "coffee roaster", "single origin coffee"] },
  { title: "Açaí & Smoothie Bowl Café", oneLiner: "Health-forward café specializing in açaí bowls, fresh juices, and smoothie flights", keywords: ["acai bowl near me", "smoothie cafe", "juice bar"] },
  { title: "Book & Brunch Café", oneLiner: "Café combining a curated bookshop with weekend brunch and specialty coffee", keywords: ["book cafe near me", "brunch cafe", "bookshop coffee"] },

  // Meal Prep & Subscription
  { title: "Weekly Meal Prep for Busy Families", oneLiner: "Family-sized healthy meals delivered Sunday — just reheat and serve throughout the week", keywords: ["family meal prep delivery", "weekly meal delivery", "healthy family meals"] },
  { title: "Cultural Cuisine Meal Kit Box", oneLiner: "Monthly subscription exploring a different world cuisine with pre-portioned ingredients and recipes", keywords: ["meal kit delivery", "cooking subscription box", "international meal kit"] },
  { title: "Postpartum Nutrition Delivery", oneLiner: "Nutrient-dense meals designed by dietitians for new mothers during recovery", keywords: ["postpartum meal delivery", "new mom food delivery", "postnatal nutrition"] },
  { title: "Senior Nutrition Meal Service", oneLiner: "Balanced, easy-to-eat meals delivered to elderly residents with dietary restriction support", keywords: ["senior meal delivery", "elderly food delivery", "meals for seniors"] },
  { title: "Athlete Meal Prep Subscription", oneLiner: "Performance-optimized meals with precise macros, tailored to training phases", keywords: ["athlete meal prep", "sports nutrition delivery", "bodybuilding meal delivery"] },
  { title: "Office Lunch Subscription", oneLiner: "Daily fresh lunch boxes delivered to workplaces with rotating menus and dietary filters", keywords: ["office lunch delivery", "corporate meal subscription", "workplace lunch service"] },

  // Beverage Brand
  { title: "Functional Mushroom Coffee Brand", oneLiner: "Coffee blended with lion's mane, chaga, and reishi for focus and immunity", keywords: ["mushroom coffee", "functional coffee", "adaptogen coffee"] },
  { title: "Small-Batch Kombucha Brewery", oneLiner: "Locally brewed kombucha with creative seasonal flavors sold in taprooms and retail", keywords: ["kombucha near me", "craft kombucha", "local kombucha brewery"] },
  { title: "Cold-Pressed Juice Delivery", oneLiner: "Weekly cold-pressed juice cleanses and daily juice subscriptions delivered to your door", keywords: ["cold pressed juice delivery", "juice cleanse", "fresh juice delivery"] },
  { title: "Craft Non-Alcoholic Beer Brand", oneLiner: "Full-flavored craft beer brewed without alcohol for the sober-curious market", keywords: ["non alcoholic beer", "craft na beer", "alcohol free beer"] },
  { title: "Premium Iced Tea Brand", oneLiner: "Artisan bottled iced teas with real fruit and botanicals — zero artificial ingredients", keywords: ["premium iced tea", "artisan tea brand", "natural iced tea"] },
  { title: "Protein Smoothie Bar & Brand", oneLiner: "Walk-up smoothie bar plus bottled protein smoothie line for retail distribution", keywords: ["protein smoothie bar", "smoothie near me", "protein shake brand"] },

  // Food Product & Packaged Goods
  { title: "Artisan Hot Sauce Line", oneLiner: "Small-batch fermented hot sauces with unique flavor profiles — farm to bottle", keywords: ["artisan hot sauce", "small batch hot sauce", "craft hot sauce"] },
  { title: "Heritage Spice Blend Company", oneLiner: "Culturally authentic spice blends with traceable, single-origin ingredients", keywords: ["spice blend company", "artisan spices", "gourmet seasoning"] },
  { title: "Gourmet Pasta & Sauce DTC", oneLiner: "Fresh artisan pasta and house-made sauces shipped directly to consumers", keywords: ["fresh pasta delivery", "gourmet pasta", "artisan pasta sauce"] },
  { title: "Healthy Snack Bar Brand", oneLiner: "Clean-label protein bars with transparent ingredients and no artificial sweeteners", keywords: ["healthy snack bar", "protein bar brand", "clean label snacks"] },
  { title: "Specialty Olive Oil Brand", oneLiner: "Single-estate, cold-pressed olive oil with tasting notes and harvest-date transparency", keywords: ["premium olive oil", "artisan olive oil", "extra virgin olive oil brand"] },
  { title: "Freeze-Dried Meal Brand", oneLiner: "Gourmet freeze-dried meals for camping, emergency prep, and quick healthy dinners", keywords: ["freeze dried meals", "camping food", "emergency food supply"] },
  { title: "Nut Butter Subscription", oneLiner: "Small-batch, flavored nut butters (maple pecan, espresso almond) delivered monthly", keywords: ["artisan nut butter", "gourmet peanut butter", "nut butter subscription"] },
  { title: "Homemade Jam & Preserves Line", oneLiner: "Seasonal, small-batch jams and preserves using locally foraged and farmed fruits", keywords: ["artisan jam", "homemade preserves", "small batch jam"] },

  // Food Tech & SaaS
  { title: "Restaurant Inventory AI", oneLiner: "AI predicts ingredient demand and auto-orders from suppliers to minimize food waste", keywords: ["restaurant inventory management", "food waste reduction software", "restaurant supply chain"] },
  { title: "Kitchen Display System for Ghost Kitchens", oneLiner: "Multi-brand order management dashboard aggregating Uber Eats, DoorDash, and direct orders", keywords: ["kitchen display system", "ghost kitchen software", "restaurant order management"] },
  { title: "Food Truck Route Optimizer", oneLiner: "AI-powered route planning for food trucks based on events, foot traffic, and weather", keywords: ["food truck app", "food truck location finder", "mobile food vendor software"] },
  { title: "Restaurant Review Analytics Platform", oneLiner: "Aggregate and analyze reviews across Google, Yelp, and TripAdvisor with AI sentiment analysis", keywords: ["restaurant review management", "review analytics", "reputation management restaurant"] },
  { title: "Digital Menu & QR Ordering System", oneLiner: "Contactless ordering and payment via QR code menus with built-in upselling AI", keywords: ["qr code menu", "digital menu restaurant", "contactless ordering system"] },
  { title: "Shared Kitchen Booking Platform", oneLiner: "Airbnb for commercial kitchens — food entrepreneurs book licensed kitchen time hourly", keywords: ["shared commercial kitchen", "kitchen rental near me", "commercial kitchen booking"] },

  // Grocery & Specialty Retail
  { title: "Organic Zero-Waste Grocery", oneLiner: "Package-free grocery store with refill stations for grains, oils, spices, and cleaning products", keywords: ["zero waste grocery store", "bulk food store", "package free grocery"] },
  { title: "Artisan Cheese Shop & Tasting Room", oneLiner: "Curated selection of local and imported cheeses with guided tasting experiences", keywords: ["cheese shop near me", "artisan cheese", "cheese tasting"] },
  { title: "Craft Chocolate Shop", oneLiner: "Bean-to-bar chocolate made on-site with single-origin cacao and tasting flights", keywords: ["craft chocolate", "bean to bar chocolate", "artisan chocolate shop"] },
  { title: "Asian Grocery & Food Hall", oneLiner: "Specialty Asian grocery with attached food court serving authentic regional dishes", keywords: ["asian grocery store", "asian food market", "asian supermarket near me"] },
  { title: "Local Honey & Apiary Shop", oneLiner: "Hyperlocal raw honey varieties with beekeeping workshops and honey tasting bar", keywords: ["local honey near me", "raw honey shop", "artisan honey"] },
  { title: "Gourmet Olive Oil & Vinegar Tasting Bar", oneLiner: "Self-serve tasting bar with 50+ infused olive oils and balsamic vinegars plus retail sales", keywords: ["olive oil tasting", "gourmet olive oil store", "balsamic vinegar shop"] },
  { title: "Ethnic Spice Market", oneLiner: "Specialty spice shop with rare ingredients, custom blends, and cooking class workshops", keywords: ["spice shop near me", "specialty spices", "ethnic grocery store"] },
  { title: "Farm Stand & CSA Pickup Hub", oneLiner: "Urban farm stand with weekly CSA boxes from local farms and artisan food producers", keywords: ["farm stand near me", "csa box delivery", "local farm produce"] },
];

const RISKS_POOL = [
  "Restaurant market may be saturated in this area — competitor density is high",
  "Food cost inflation could squeeze margins below viability",
  "Health permit and licensing delays may push launch back 3-6 months",
  "Delivery platform commissions (15-30%) significantly reduce margins",
  "Staff turnover in food service averages 70-80% annually",
  "Seasonal demand fluctuations may create cash flow gaps",
  "Food safety incident could cause irreparable reputation damage",
  "Supply chain disruption for key ingredients is an ongoing risk",
  "Changing food trends could make the concept feel dated within 1-2 years",
  "Rent escalation in high-foot-traffic locations could erode profitability",
  "Food waste from perishable inventory requires careful management",
  "Dependency on a single delivery platform creates platform risk",
];

const NEXT_STEPS_POOL = [
  "Run a pop-up or food market stall to test menu and pricing with real customers",
  "Interview 20 potential customers about their dining habits and pain points",
  "Research local health permit requirements and timeline for your city",
  "Visit 5 direct competitors and analyze menu, pricing, and customer experience",
  "Source 3 potential suppliers and compare pricing, reliability, and minimum orders",
  "Calculate unit economics: food cost %, labor cost %, and break-even point",
  "Test 3 menu items with a focus group and gather feedback on taste and pricing",
  "Create a delivery-only brand on Uber Eats or DoorDash to validate demand",
  "Build a social media presence with food photography and behind-the-scenes content",
  "Explore shared commercial kitchen options to minimize upfront investment",
  "Develop a minimum viable menu (5-8 items) that can be executed with 2-3 staff",
  "Run a pre-sale or waitlist campaign to gauge local interest before committing",
];

function getVerdict(score: number): "strong" | "promising" | "risky" | "weak" {
  if (score >= 75) return "strong";
  if (score >= 55) return "promising";
  if (score >= 35) return "risky";
  return "weak";
}

export function generateIdeasPool(): LeaderboardIdea[] {
  const ideas: LeaderboardIdea[] = [];

  for (let i = 0; i < IDEA_TEMPLATES.length; i++) {
    const template = IDEA_TEMPLATES[i];
    const seed = hash(template.title);
    const category = pickRandom(CATEGORIES, seed);
    const location = pickRandom(POPULAR_LOCATIONS, seed + 1);

    const overallScore = seededRange(seed + 2, 25, 95);
    const demandScore = seededRange(seed + 3, 20, 98);
    const competitionScore = seededRange(seed + 4, 15, 95);
    const monetizationScore = seededRange(seed + 5, 20, 95);
    const timingScore = seededRange(seed + 6, 25, 95);

    const riskStart = seed % (RISKS_POOL.length - 2);
    const stepStart = (seed + 3) % (NEXT_STEPS_POOL.length - 2);

    ideas.push({
      id: generateId("idea", i),
      title: template.title,
      oneLiner: template.oneLiner,
      category,
      location,
      overallScore,
      demandScore,
      competitionScore,
      monetizationScore,
      timingScore,
      totalVolume: seededRange(seed + 7, 500, 80000),
      avgCPC: Math.round(seededRange(seed + 8, 50, 1500)) / 100,
      avgCompetition: seededRange(seed + 9, 10, 90),
      verdict: getVerdict(overallScore),
      validatedAt: randomDate(seed + 10, 90),
      upvotes: seededRange(seed + 11, 3, 280),
      bookmarks: seededRange(seed + 12, 1, 120),
      keyRisks: RISKS_POOL.slice(riskStart, riskStart + 3),
      nextSteps: NEXT_STEPS_POOL.slice(stepStart, stepStart + 3),
      keywords: template.keywords,
    });
  }

  return ideas.sort((a, b) => b.overallScore - a.overallScore);
}

import { hash as h, seededRange as sr } from "./helpers";
export { h as _hash, sr as _seededRange };

let _cachedPool: LeaderboardIdea[] | null = null;

export function getIdeasPool(): LeaderboardIdea[] {
  if (!_cachedPool) {
    _cachedPool = generateIdeasPool();
  }
  return _cachedPool;
}
