import { CATEGORIES, POPULAR_LOCATIONS } from "@/lib/constants";
import { hash, seededRange, pickRandom, generateId, randomDate } from "./helpers";
import type { LeaderboardIdea } from "@/types/leaderboard";

const IDEA_TEMPLATES: { title: string; oneLiner: string; keywords: string[] }[] = [
  { title: "AI Meal Planner for Busy Professionals", oneLiner: "Personalized weekly meal plans generated by AI based on dietary goals and local grocery prices", keywords: ["meal planning app", "ai diet planner", "weekly meal prep"] },
  { title: "Pet Sitting Marketplace", oneLiner: "On-demand pet care platform connecting pet owners with vetted local sitters", keywords: ["pet sitting near me", "dog sitter app", "pet care marketplace"] },
  { title: "Micro-SaaS for Freelancer Invoicing", oneLiner: "Dead-simple invoicing tool built specifically for solo freelancers", keywords: ["freelancer invoice tool", "simple invoicing app", "freelance billing"] },
  { title: "Sustainable Fashion Rental", oneLiner: "Rent designer clothing for events instead of buying — reducing fashion waste", keywords: ["rent designer dress", "fashion rental service", "sustainable fashion"] },
  { title: "Local Farm-to-Table Delivery", oneLiner: "Weekly boxes of seasonal produce delivered directly from nearby farms", keywords: ["farm to table delivery", "local produce box", "organic farm delivery"] },
  { title: "AI-Powered Resume Builder", oneLiner: "Generate ATS-optimized resumes tailored to specific job descriptions in seconds", keywords: ["ai resume builder", "ats resume tool", "resume generator"] },
  { title: "Virtual Interior Design Studio", oneLiner: "Upload a photo of your room and get AI-designed makeover suggestions with shopping links", keywords: ["virtual interior design", "room makeover app", "ai home design"] },
  { title: "Niche Newsletter Monetization Platform", oneLiner: "All-in-one tool to create, grow, and monetize niche email newsletters", keywords: ["newsletter platform", "email monetization", "newsletter tools"] },
  { title: "Smart Parking Finder", oneLiner: "Real-time parking availability and reservation system for congested urban areas", keywords: ["find parking near me", "parking reservation app", "smart parking"] },
  { title: "Online Language Tutoring for Kids", oneLiner: "Fun, game-based language lessons with native speakers for children ages 5-12", keywords: ["kids language tutor", "online language classes kids", "children language learning"] },
  { title: "Home EV Charging Installation", oneLiner: "End-to-end service for installing home electric vehicle chargers with permit handling", keywords: ["ev charger installation", "home ev charging", "electric car charger install"] },
  { title: "Subscription Snack Box for Offices", oneLiner: "Curated healthy snack deliveries for office break rooms on a monthly subscription", keywords: ["office snack delivery", "healthy snack subscription", "workplace snack box"] },
  { title: "AI Personal Finance Coach", oneLiner: "Conversational AI that analyzes spending patterns and gives actionable saving advice", keywords: ["ai financial advisor", "personal finance app", "money saving app"] },
  { title: "Senior Tech Support Service", oneLiner: "Patient, on-demand tech help for seniors — from setting up phones to video calling", keywords: ["tech support for seniors", "elderly tech help", "senior phone setup"] },
  { title: "Pop-Up Event Space Marketplace", oneLiner: "Book unique venues for pop-up shops, workshops, and private events by the hour", keywords: ["pop up venue rental", "event space booking", "hourly venue rental"] },
  { title: "Eco-Friendly Cleaning Products DTC", oneLiner: "Refillable, plant-based cleaning products shipped to your door in zero-waste packaging", keywords: ["eco cleaning products", "refillable cleaning", "sustainable cleaning supplies"] },
  { title: "Mental Health Journaling App", oneLiner: "Guided journaling prompts with mood tracking and AI-powered emotional insights", keywords: ["mental health journal app", "mood tracker", "guided journaling"] },
  { title: "Dog Walking & GPS Tracking App", oneLiner: "Book insured dog walkers and watch your dog's walk live on a map", keywords: ["dog walking app", "dog walker near me", "pet walking service"] },
  { title: "Local Tour Guide Marketplace", oneLiner: "Connect travelers with passionate locals for authentic, off-the-beaten-path experiences", keywords: ["local tour guide", "private city tour", "authentic local experiences"] },
  { title: "Kids Coding Bootcamp Platform", oneLiner: "Interactive online coding courses designed for kids aged 8-16 with project-based learning", keywords: ["kids coding classes", "coding for children", "learn to code kids"] },
  { title: "Automated Bookkeeping for Small Biz", oneLiner: "AI categorizes transactions, reconciles accounts, and generates tax-ready reports", keywords: ["small business bookkeeping", "automated accounting", "ai bookkeeper"] },
  { title: "Fitness Class Aggregator", oneLiner: "Search and book fitness classes across gyms, studios, and outdoor sessions in one app", keywords: ["fitness classes near me", "gym class booking", "workout class finder"] },
  { title: "Remote Team Building Platform", oneLiner: "Virtual escape rooms, trivia, and collaborative games for distributed teams", keywords: ["virtual team building", "remote team activities", "online team games"] },
  { title: "Custom Gift Curation Service", oneLiner: "AI-powered gift recommendations based on recipient personality and occasion", keywords: ["personalized gift ideas", "custom gift service", "gift recommendation"] },
  { title: "Urban Rooftop Farming Kits", oneLiner: "Ready-to-grow modular garden kits designed for apartment balconies and rooftops", keywords: ["rooftop garden kit", "urban farming", "balcony garden"] },
  { title: "On-Demand Handyman App", oneLiner: "Book verified handymen for small home repairs within 2 hours", keywords: ["handyman near me", "home repair service", "on demand handyman"] },
  { title: "AI Study Buddy for University Students", oneLiner: "Upload lecture notes and get AI-generated flashcards, quizzes, and study plans", keywords: ["ai study tool", "student flashcard app", "exam prep ai"] },
  { title: "Vintage Furniture Restoration Service", oneLiner: "Mail in or drop off old furniture and get it professionally restored and refinished", keywords: ["furniture restoration near me", "vintage furniture repair", "refinish old furniture"] },
  { title: "Neighborhood Safety Alert App", oneLiner: "Hyperlocal crime alerts and community safety reporting for your exact neighborhood", keywords: ["neighborhood safety app", "local crime alerts", "community safety"] },
  { title: "Plant Care Subscription & Advice", oneLiner: "Monthly plant delivery with a care app that identifies diseases and sends watering reminders", keywords: ["plant subscription box", "plant care app", "indoor plant delivery"] },
  { title: "Coworking Space Booking Platform", oneLiner: "Find and book coworking desks, meeting rooms, and private offices by the hour", keywords: ["coworking near me", "book desk space", "hourly office rental"] },
  { title: "Personalized Vitamin Subscription", oneLiner: "Take a health quiz and receive custom vitamin packs delivered monthly", keywords: ["personalized vitamins", "custom supplement pack", "vitamin subscription"] },
  { title: "Electric Bike Rental Network", oneLiner: "Dockless e-bike rentals with dedicated lanes and charging stations across the city", keywords: ["electric bike rental", "e-bike near me", "city bike rental"] },
  { title: "AI Logo & Brand Kit Generator", oneLiner: "Generate professional logos, color palettes, and brand guidelines in minutes with AI", keywords: ["ai logo maker", "brand kit generator", "logo design tool"] },
  { title: "Micro-Influencer Campaign Platform", oneLiner: "Connect brands with nano/micro-influencers for authentic, affordable social campaigns", keywords: ["micro influencer platform", "influencer marketing tool", "find small influencers"] },
  { title: "Elderly Companion Matching Service", oneLiner: "Match seniors with vetted companions for social visits, errands, and light assistance", keywords: ["elderly companion service", "senior companionship", "companion care near me"] },
  { title: "Smart Home Energy Audit Tool", oneLiner: "Analyze your utility bills and smart meter data to find energy-saving opportunities", keywords: ["home energy audit", "reduce electricity bill", "energy saving tool"] },
  { title: "Artisan Bread Subscription", oneLiner: "Weekly sourdough and specialty bread delivered from local micro-bakeries", keywords: ["bread subscription", "artisan bread delivery", "sourdough delivery"] },
  { title: "AI-Powered Property Valuation", oneLiner: "Get instant, accurate property valuations using AI analysis of market data and comparables", keywords: ["property valuation tool", "home value estimator", "real estate ai"] },
  { title: "Children's Party Planning Platform", oneLiner: "Book entertainers, venues, cakes, and decorations for kids' parties in one place", keywords: ["kids party planner", "children's party booking", "party planning service"] },
  { title: "B2B SaaS for Restaurant Inventory", oneLiner: "AI predicts ingredient demand and automates supplier orders to reduce food waste", keywords: ["restaurant inventory management", "food waste reduction", "restaurant supply chain"] },
  { title: "Mobile Car Detailing Service", oneLiner: "Professional car detailing that comes to your driveway or office parking lot", keywords: ["mobile car detailing", "car wash near me", "auto detailing service"] },
  { title: "Meditation & Breathwork App", oneLiner: "Science-backed breathing exercises and guided meditations for stress relief", keywords: ["meditation app", "breathwork exercises", "stress relief app"] },
  { title: "Freelance Developer Vetting Platform", oneLiner: "Pre-screened, tested freelance developers matched to projects in 48 hours", keywords: ["hire freelance developer", "vetted developer platform", "freelance coding"] },
  { title: "Subscription Flower Delivery", oneLiner: "Seasonal bouquets sourced from local growers delivered bi-weekly to your door", keywords: ["flower subscription", "flower delivery service", "weekly bouquet"] },
  { title: "AI Customer Support Chatbot Builder", oneLiner: "No-code tool to build AI chatbots trained on your docs for instant customer support", keywords: ["ai chatbot builder", "customer support bot", "no code chatbot"] },
  { title: "Shared Kitchen Space for Food Startups", oneLiner: "Hourly kitchen rentals for food entrepreneurs to cook, test, and produce", keywords: ["shared commercial kitchen", "kitchen rental near me", "cloud kitchen space"] },
  { title: "Sports League Management App", oneLiner: "Schedule games, track scores, manage rosters, and collect fees for amateur sports leagues", keywords: ["sports league app", "team management tool", "league scheduling"] },
  { title: "Luxury Picnic Setup Service", oneLiner: "Book a fully decorated, Instagram-worthy picnic set up in a scenic location", keywords: ["luxury picnic setup", "picnic planning service", "outdoor picnic experience"] },
  { title: "AI-Powered SEO Content Writer", oneLiner: "Generate SEO-optimized blog posts and landing pages from just a target keyword", keywords: ["ai seo writer", "content writing tool", "seo blog generator"] },
  { title: "Zero-Waste Grocery Store Online", oneLiner: "Package-free groceries and bulk goods delivered in reusable containers", keywords: ["zero waste grocery", "bulk food online", "plastic free shopping"] },
  { title: "Smart Baby Monitor with AI", oneLiner: "Baby monitor that uses AI to detect cries, breathing anomalies, and sleep patterns", keywords: ["smart baby monitor", "ai baby monitor", "infant sleep tracker"] },
  { title: "Corporate Wellness Platform", oneLiner: "All-in-one employee wellness: fitness challenges, mental health resources, and health tracking", keywords: ["corporate wellness program", "employee wellness platform", "workplace health"] },
  { title: "Local Craft Beer Subscription", oneLiner: "Monthly selection of craft beers from local microbreweries delivered chilled", keywords: ["craft beer subscription", "local beer delivery", "beer of the month"] },
  { title: "AI Homework Helper for Parents", oneLiner: "Scan homework problems and get step-by-step explanations to help your kids learn", keywords: ["homework help app", "math solver for parents", "ai tutor app"] },
  { title: "Solar Panel Cleaning Service", oneLiner: "Professional solar panel cleaning to maintain optimal energy output", keywords: ["solar panel cleaning", "clean solar panels", "solar maintenance service"] },
  { title: "Secondhand Electronics Marketplace", oneLiner: "Buy and sell refurbished electronics with quality guarantees and easy returns", keywords: ["refurbished electronics", "used phone marketplace", "secondhand laptop"] },
  { title: "Virtual Event Photography", oneLiner: "Remote photo direction service for events — a photographer guides attendees via video", keywords: ["virtual photographer", "remote event photos", "online photography service"] },
  { title: "AI-Powered Wardrobe Stylist", oneLiner: "Upload your closet and get daily outfit suggestions based on weather, events, and style", keywords: ["ai wardrobe stylist", "outfit recommendation app", "virtual stylist"] },
  { title: "Drone Photography for Real Estate", oneLiner: "Aerial photography and video tours for property listings at affordable prices", keywords: ["drone real estate photography", "aerial property photos", "real estate drone"] },
  { title: "Specialty Coffee Subscription", oneLiner: "Single-origin beans from award-winning roasters delivered fresh every two weeks", keywords: ["coffee subscription", "specialty coffee delivery", "fresh coffee beans"] },
  { title: "Personal Shopper for Groceries", oneLiner: "A dedicated shopper who knows your preferences and handles weekly grocery runs", keywords: ["personal grocery shopper", "grocery delivery service", "personal shopping"] },
  { title: "AI Music Practice Coach", oneLiner: "Listens to you play and gives real-time feedback on pitch, rhythm, and technique", keywords: ["music practice app", "ai music teacher", "learn instrument app"] },
  { title: "Micro-Apartment Furniture Design", oneLiner: "Space-saving, modular furniture designed specifically for studios under 400 sq ft", keywords: ["small space furniture", "micro apartment design", "space saving furniture"] },
  { title: "Neighborhood Tool Library", oneLiner: "Borrow power tools, gardening equipment, and specialty items from a shared community inventory", keywords: ["tool library near me", "borrow tools", "community tool sharing"] },
  { title: "Automated Social Media Scheduler", oneLiner: "AI analyzes your audience and auto-posts content at optimal times across platforms", keywords: ["social media scheduler", "auto post tool", "social media automation"] },
  { title: "Premium Dog Food Subscription", oneLiner: "Vet-formulated, human-grade dog food customized to your dog's breed, age, and allergies", keywords: ["custom dog food", "premium dog food delivery", "personalized pet food"] },
  { title: "Remote Notary Service", oneLiner: "Get documents notarized via secure video call — legally valid in all 50 states", keywords: ["online notary", "remote notarization", "virtual notary service"] },
  { title: "AI-Powered Job Interview Coach", oneLiner: "Practice interviews with an AI that gives feedback on answers, body language, and confidence", keywords: ["interview practice app", "ai interview coach", "job interview prep"] },
  { title: "Hyperlocal Weather Alerts for Events", oneLiner: "Micro-weather forecasts for specific venues to help outdoor event planning", keywords: ["hyperlocal weather", "event weather forecast", "outdoor event planning"] },
  { title: "Digital Detox Retreat Booking", oneLiner: "Book screen-free wellness retreats with meditation, nature hikes, and journaling workshops", keywords: ["digital detox retreat", "wellness retreat booking", "screen free vacation"] },
  { title: "AI Tax Filing for Gig Workers", oneLiner: "Automated tax deduction tracking and filing optimized for freelancers and gig workers", keywords: ["gig worker tax filing", "freelance tax app", "self employed taxes"] },
  { title: "Peer-to-Peer Storage Marketplace", oneLiner: "Rent unused garage and closet space from neighbors for affordable storage", keywords: ["peer to peer storage", "cheap storage near me", "rent storage space"] },
  { title: "Custom Protein Bar Builder", oneLiner: "Design your own protein bars — choose ingredients, flavors, and macros, delivered monthly", keywords: ["custom protein bars", "build your own protein bar", "personalized nutrition"] },
  { title: "Voice-First Smart Home Setup Service", oneLiner: "Professional installation and configuration of Alexa, Google Home, and smart devices", keywords: ["smart home setup", "alexa installation", "home automation service"] },
  { title: "Vertical Farming Consulting", oneLiner: "Help restaurants and grocers set up profitable indoor vertical farms", keywords: ["vertical farming consulting", "indoor farm setup", "urban agriculture"] },
  { title: "AI Wedding Planner", oneLiner: "AI-powered wedding planning tool that manages vendors, timelines, budgets, and seating", keywords: ["ai wedding planner", "wedding planning app", "wedding budget tool"] },
  { title: "Elderly Fall Detection Wearable", oneLiner: "Lightweight wearable that detects falls and automatically alerts family and emergency services", keywords: ["fall detection device", "elderly safety wearable", "senior fall alert"] },
  { title: "Local Experience Gift Cards", oneLiner: "Gift cards redeemable at curated local restaurants, spas, and adventure experiences", keywords: ["experience gift card", "local gift voucher", "activity gift card"] },
  { title: "AI-Powered Price Comparison Tool", oneLiner: "Scan any product and instantly compare prices across 50+ retailers including shipping", keywords: ["price comparison tool", "price checker app", "compare prices online"] },
  { title: "Sustainable Period Products Subscription", oneLiner: "Organic, biodegradable period products delivered discreetly on your cycle schedule", keywords: ["organic period products", "sustainable menstrual products", "period subscription box"] },
  { title: "Home Renovation Cost Estimator", oneLiner: "Get instant, accurate renovation cost estimates with AI analysis of your project scope", keywords: ["renovation cost calculator", "home remodel estimate", "construction cost tool"] },
  { title: "Niche Podcast Production Service", oneLiner: "End-to-end podcast production — editing, show notes, distribution, and growth strategy", keywords: ["podcast production service", "podcast editing", "podcast launch service"] },
  { title: "AI-Powered Outfit-of-the-Day for Ecommerce", oneLiner: "Plugin for fashion stores that shows AI-curated daily outfit suggestions from their catalog", keywords: ["fashion ai plugin", "outfit recommendation engine", "ecommerce personalization"] },
  { title: "Student Housing Marketplace", oneLiner: "Find and book verified student rooms, apartments, and co-living spaces near universities", keywords: ["student housing", "rooms near university", "student accommodation"] },
  { title: "Hyperlocal News Aggregator", oneLiner: "AI curates news, events, and discussions from your specific neighborhood", keywords: ["local news app", "neighborhood news", "hyperlocal news"] },
  { title: "Carbon Footprint Tracker", oneLiner: "Track your daily carbon footprint from food, travel, and purchases with actionable reduction tips", keywords: ["carbon footprint calculator", "carbon tracker app", "reduce carbon footprint"] },
  { title: "AI Business Name Generator", oneLiner: "Generate creative, available business names with instant domain and trademark checks", keywords: ["business name generator", "company name ideas", "brand name tool"] },
  { title: "Mobile Vet Clinic", oneLiner: "Licensed veterinarians that come to your home for check-ups, vaccines, and minor treatments", keywords: ["mobile vet near me", "home vet visit", "at home veterinary"] },
  { title: "Sleep Optimization App", oneLiner: "AI analyzes sleep data from wearables and creates personalized protocols for better sleep", keywords: ["sleep improvement app", "sleep optimization", "better sleep tool"] },
  { title: "Subscription Art Prints for Homes", oneLiner: "Monthly curated art prints from emerging artists shipped with museum-quality framing", keywords: ["art subscription", "monthly art prints", "wall art delivery"] },
  { title: "AI Meeting Notes & Action Items", oneLiner: "Record meetings and get AI-generated summaries, action items, and follow-up tasks", keywords: ["ai meeting notes", "meeting summary tool", "automated meeting minutes"] },
  { title: "Outdoor Adventure Gear Rental", oneLiner: "Rent camping, hiking, and ski gear by the weekend instead of buying expensive equipment", keywords: ["outdoor gear rental", "camping equipment rental", "rent hiking gear"] },
  { title: "Personalized Children's Book Creator", oneLiner: "Create custom storybooks starring your child with AI-generated illustrations", keywords: ["personalized children's book", "custom kids book", "create storybook"] },
  { title: "Smart Water Leak Detection System", oneLiner: "IoT sensors that detect leaks early and auto-shut water valves to prevent damage", keywords: ["water leak detector", "smart water sensor", "leak prevention system"] },
  { title: "Gourmet Meal Kit for Date Nights", oneLiner: "Chef-designed, restaurant-quality meal kits for two with wine pairing suggestions", keywords: ["date night meal kit", "gourmet cooking kit", "couples meal delivery"] },
  { title: "AI-Powered Legal Document Generator", oneLiner: "Generate contracts, NDAs, and legal templates customized to your jurisdiction", keywords: ["legal document generator", "contract template tool", "ai legal documents"] },
  { title: "Electric Scooter Repair Service", oneLiner: "Mobile repair and maintenance for personal e-scooters and e-bikes", keywords: ["electric scooter repair", "e-scooter maintenance", "scooter fix near me"] },
  { title: "AI Dermatology Skin Check", oneLiner: "Upload a photo of a skin concern and get AI-powered analysis with dermatologist recommendations", keywords: ["ai skin checker", "online dermatology", "skin condition app"] },
];

const RISKS_POOL = [
  "Market may be too saturated in major metros",
  "Customer acquisition cost could be high initially",
  "Regulatory requirements vary by region",
  "Seasonal demand fluctuations possible",
  "Requires significant initial content investment",
  "User trust takes time to build in this category",
  "Competition from well-funded incumbents",
  "Technology costs may scale non-linearly",
  "Retention depends heavily on first experience",
  "Price sensitivity in target demographic",
  "Supply-side marketplace dynamics are challenging",
  "Long sales cycle for B2B customers",
];

const NEXT_STEPS_POOL = [
  "Build an MVP landing page and run Google Ads to test conversion",
  "Interview 20 potential customers to validate pain point",
  "Analyze top 5 competitors' pricing and positioning",
  "Create a waitlist and measure sign-up velocity",
  "Build a no-code prototype and test with 50 users",
  "Run a small pilot in one neighborhood before scaling",
  "Partner with a complementary business for initial distribution",
  "Set up analytics and define core success metrics",
  "Create content marketing funnel with SEO-optimized blog",
  "Test unit economics with a manual version of the service",
  "Build social proof through early testimonials and case studies",
  "Secure 3 letter-of-intent customers before building",
];

function getVerdict(score: number): "strong" | "promising" | "risky" | "weak" {
  if (score >= 75) return "strong";
  if (score >= 55) return "promising";
  if (score >= 35) return "risky";
  return "weak";
}

export function generateIdeasPool(): LeaderboardIdea[] {
  const ideas: LeaderboardIdea[] = [];

  for (let i = 0; i < IDEA_TEMPLATES.length; i++) {
    const template = IDEA_TEMPLATES[i];
    const seed = hash(template.title);
    const category = pickRandom(CATEGORIES, seed);
    const location = pickRandom(POPULAR_LOCATIONS, seed + 1);

    const overallScore = seededRange(seed + 2, 25, 95);
    const demandScore = seededRange(seed + 3, 20, 98);
    const competitionScore = seededRange(seed + 4, 15, 95);
    const monetizationScore = seededRange(seed + 5, 20, 95);
    const timingScore = seededRange(seed + 6, 25, 95);

    const riskStart = seed % (RISKS_POOL.length - 2);
    const stepStart = (seed + 3) % (NEXT_STEPS_POOL.length - 2);

    ideas.push({
      id: generateId("idea", i),
      title: template.title,
      oneLiner: template.oneLiner,
      category,
      location,
      overallScore,
      demandScore,
      competitionScore,
      monetizationScore,
      timingScore,
      totalVolume: seededRange(seed + 7, 500, 80000),
      avgCPC: Math.round(seededRange(seed + 8, 50, 1500)) / 100,
      avgCompetition: seededRange(seed + 9, 10, 90),
      verdict: getVerdict(overallScore),
      validatedAt: randomDate(seed + 10, 90),
      upvotes: seededRange(seed + 11, 3, 280),
      bookmarks: seededRange(seed + 12, 1, 120),
      keyRisks: RISKS_POOL.slice(riskStart, riskStart + 3),
      nextSteps: NEXT_STEPS_POOL.slice(stepStart, stepStart + 3),
      keywords: template.keywords,
    });
  }

  return ideas.sort((a, b) => b.overallScore - a.overallScore);
}

import { hash as h, seededRange as sr } from "./helpers";
export { h as _hash, sr as _seededRange };

let _cachedPool: LeaderboardIdea[] | null = null;

export function getIdeasPool(): LeaderboardIdea[] {
  if (!_cachedPool) {
    _cachedPool = generateIdeasPool();
  }
  return _cachedPool;
}
