import type { SuccessStory } from "@/types/analysis";

export function getSuccessStories(): SuccessStory[] {
  return [
    {
      id: "ss_1",
      companyName: "FreshBowl",
      founderName: "Maria Chen",
      ideaOrigin: "Healthy meal prep delivery for busy professionals",
      category: "Meal Prep & Subscription",
      location: "Los Angeles, USA",
      yearFounded: 2021,
      currentRevenue: "$2.4M ARR",
      employeeCount: 18,
      keyInsight: "Started by validating demand with a simple Google Form and Instagram ads. Hit 100 orders in the first week.",
      timeline: [
        { year: 2021, milestone: "Launched with 3 meal options and local delivery" },
        { year: 2022, milestone: "Expanded to 5 neighborhoods, reached $50K MRR" },
        { year: 2023, milestone: "Raised seed round, launched subscription model" },
        { year: 2024, milestone: "Expanded to 3 cities, $200K MRR" },
      ],
      logoColor: "#22c55e",
    },
    {
      id: "ss_2",
      companyName: "CloudBite",
      founderName: "James O'Brien",
      ideaOrigin: "Multi-brand ghost kitchen for delivery-only concepts",
      category: "Ghost Kitchen & Delivery-Only",
      location: "London, UK",
      yearFounded: 2022,
      currentRevenue: "$1.8M ARR",
      employeeCount: 22,
      keyInsight: "Ran 4 virtual brands from one kitchen — each targeting a different cuisine. 'Korean fried chicken delivery' had 15K monthly searches with zero good options.",
      timeline: [
        { year: 2022, milestone: "Launched 2 brands on Deliveroo from a shared kitchen" },
        { year: 2023, milestone: "Added 2 more brands, moved to own kitchen space" },
        { year: 2024, milestone: "£120K MRR, expanded to Manchester" },
      ],
      logoColor: "#3b82f6",
    },
    {
      id: "ss_3",
      companyName: "Rise & Knead",
      founderName: "Priya Sharma",
      ideaOrigin: "Artisan sourdough micro-bakery with local delivery",
      category: "Bakery & Pastry",
      location: "Mumbai, India",
      yearFounded: 2021,
      currentRevenue: "$450K ARR",
      employeeCount: 8,
      keyInsight: "Started baking from home during lockdown. Instagram reels of the bread-making process went viral and drove all initial demand.",
      timeline: [
        { year: 2021, milestone: "Home bakery with 20 loaves/day, sold via WhatsApp" },
        { year: 2022, milestone: "Moved to commercial kitchen, 100 loaves/day" },
        { year: 2023, milestone: "Opened retail storefront and café" },
        { year: 2024, milestone: "Launched wholesale to 15 restaurants" },
      ],
      logoColor: "#a855f7",
    },
    {
      id: "ss_4",
      companyName: "El Fuego",
      founderName: "Carlos Rivera",
      ideaOrigin: "Mexican street food truck turned multi-location brand",
      category: "Food Truck & Street Food",
      location: "São Paulo, Brazil",
      yearFounded: 2020,
      currentRevenue: "$3.2M ARR",
      employeeCount: 35,
      keyInsight: "Validated with one food truck at weekend markets. Social media buzz and 4.9-star reviews drove demand for permanent locations.",
      timeline: [
        { year: 2020, milestone: "First food truck at weekend food markets" },
        { year: 2021, milestone: "Added second truck, launched catering arm" },
        { year: 2023, milestone: "Opened first brick-and-mortar restaurant" },
        { year: 2024, milestone: "3 locations + 2 trucks, R$1.5M monthly revenue" },
      ],
      logoColor: "#f59e0b",
    },
    {
      id: "ss_5",
      companyName: "Matcha Zen",
      founderName: "Yuki Tanaka",
      ideaOrigin: "Japanese matcha café and tea experience",
      category: "Café & Coffee Shop",
      location: "Tokyo, Japan",
      yearFounded: 2022,
      currentRevenue: "$680K ARR",
      employeeCount: 10,
      keyInsight: "'Matcha cafe' had 40K monthly searches in our area with only 2 dedicated matcha shops. Tourists and locals both craved an authentic experience.",
      timeline: [
        { year: 2022, milestone: "Opened 20-seat matcha café in Shibuya" },
        { year: 2023, milestone: "Added matcha kit DTC sales, ¥5M/month" },
        { year: 2024, milestone: "Second location near Sensoji temple" },
      ],
      logoColor: "#22c55e",
    },
    {
      id: "ss_6",
      companyName: "CraftBox",
      founderName: "Sophie Dubois",
      ideaOrigin: "Curated local craft beer and artisan food subscription",
      category: "Beverage Brand",
      location: "Paris, France",
      yearFounded: 2022,
      currentRevenue: "$420K ARR",
      employeeCount: 6,
      keyInsight: "The French craft beer scene was booming but had no discovery platform. We became the bridge between brewers and enthusiasts.",
      timeline: [
        { year: 2022, milestone: "Started with 10 local breweries, 200 subscribers" },
        { year: 2023, milestone: "Reached 2K subscribers, added tasting events" },
        { year: 2024, milestone: "Expanded to Lyon, Bordeaux, and Brussels" },
      ],
      logoColor: "#ec4899",
    },
    {
      id: "ss_7",
      companyName: "Fuego Sauces",
      founderName: "Erik Lindqvist",
      ideaOrigin: "Small-batch fermented hot sauce line",
      category: "Food Product & Packaged Goods",
      location: "Stockholm, Sweden",
      yearFounded: 2021,
      currentRevenue: "$890K ARR",
      employeeCount: 7,
      keyInsight: "Started fermenting hot sauce at home and selling at farmers markets. A single TikTok review from a food influencer generated 2,000 orders overnight.",
      timeline: [
        { year: 2021, milestone: "3 sauce varieties, sold at 5 local markets" },
        { year: 2022, milestone: "DTC website launched, 500 orders/month" },
        { year: 2023, milestone: "Retail partnerships with 40+ specialty stores" },
        { year: 2024, milestone: "Export to 8 European countries" },
      ],
      logoColor: "#ef4444",
    },
    {
      id: "ss_8",
      companyName: "KitchenOS",
      founderName: "Aisha Patel",
      ideaOrigin: "AI-powered inventory and food waste management for restaurants",
      category: "Food Tech & SaaS",
      location: "Toronto, Canada",
      yearFounded: 2022,
      currentRevenue: "$1.1M ARR",
      employeeCount: 12,
      keyInsight: "Restaurants waste 4-10% of food purchased. We proved ROI by showing a 6% food cost reduction in our pilot with 5 restaurants.",
      timeline: [
        { year: 2022, milestone: "Piloted with 5 Toronto restaurants" },
        { year: 2023, milestone: "50 restaurant clients, $40K MRR" },
        { year: 2024, milestone: "Raised seed round, expanded to Vancouver and Montreal" },
      ],
      logoColor: "#06b6d4",
    },
  ];
}
