import type { SuccessStory } from "@/types/analysis";

export function getSuccessStories(): SuccessStory[] {
  return [
    {
      id: "ss_1",
      companyName: "FreshBowl",
      founderName: "Maria Chen",
      ideaOrigin: "Healthy meal prep delivery for busy professionals",
      category: "Food & Beverage",
      location: "Los Angeles, USA",
      yearFounded: 2021,
      currentRevenue: "$2.4M ARR",
      employeeCount: 18,
      keyInsight: "Started by validating demand with a simple Google Form and Instagram ads. Hit 100 orders in the first week.",
      timeline: [
        { year: 2021, milestone: "Launched with 3 meal options and local delivery" },
        { year: 2022, milestone: "Expanded to 5 neighborhoods, reached $50K MRR" },
        { year: 2023, milestone: "Raised seed round, launched subscription model" },
        { year: 2024, milestone: "Expanded to 3 cities, $200K MRR" },
      ],
      logoColor: "#22c55e",
    },
    {
      id: "ss_2",
      companyName: "PetPal",
      founderName: "James O'Brien",
      ideaOrigin: "AI-powered pet health monitoring wearable",
      category: "Pet Services",
      location: "London, UK",
      yearFounded: 2022,
      currentRevenue: "$890K ARR",
      employeeCount: 12,
      keyInsight: "Search volume for 'pet health tracker' was growing 40% YoY with very low competition. Classic Goldilocks opportunity.",
      timeline: [
        { year: 2022, milestone: "Prototyped with off-the-shelf sensors and an app" },
        { year: 2023, milestone: "Kickstarter raised £120K in 30 days" },
        { year: 2024, milestone: "Retail partnerships with 2 major pet chains" },
      ],
      logoColor: "#3b82f6",
    },
    {
      id: "ss_3",
      companyName: "DeskHop",
      founderName: "Priya Sharma",
      ideaOrigin: "Coworking space aggregator and booking platform",
      category: "SaaS & Software",
      location: "Mumbai, India",
      yearFounded: 2020,
      currentRevenue: "$1.8M ARR",
      employeeCount: 25,
      keyInsight: "The hybrid work boom created a massive supply of empty desks. We just connected them with the people who needed them.",
      timeline: [
        { year: 2020, milestone: "Launched MVP listing 50 spaces in Mumbai" },
        { year: 2021, milestone: "Expanded to Bangalore and Delhi" },
        { year: 2022, milestone: "Added enterprise booking, $100K MRR" },
        { year: 2023, milestone: "Series A funding, expanded to SE Asia" },
      ],
      logoColor: "#a855f7",
    },
    {
      id: "ss_4",
      companyName: "GreenCharge",
      founderName: "Erik Lindqvist",
      ideaOrigin: "EV charging installation for residential buildings",
      category: "Sustainability & Green",
      location: "Stockholm, Sweden",
      yearFounded: 2021,
      currentRevenue: "$3.2M ARR",
      employeeCount: 35,
      keyInsight: "Property managers wanted a turnkey solution. We validated by knocking on 30 doors and signing 8 buildings in week one.",
      timeline: [
        { year: 2021, milestone: "First 10 buildings equipped in Stockholm" },
        { year: 2022, milestone: "Government subsidy program boosted demand 3x" },
        { year: 2023, milestone: "Expanded to Norway and Denmark" },
        { year: 2024, milestone: "100+ buildings, recurring maintenance contracts" },
      ],
      logoColor: "#f59e0b",
    },
    {
      id: "ss_5",
      companyName: "StudyBuddy AI",
      founderName: "Yuki Tanaka",
      ideaOrigin: "AI-generated flashcards and study plans from lecture notes",
      category: "Education & Training",
      location: "Tokyo, Japan",
      yearFounded: 2023,
      currentRevenue: "$650K ARR",
      employeeCount: 8,
      keyInsight: "Students were already searching for this — 'AI study tool' had 35K monthly searches with almost no good results.",
      timeline: [
        { year: 2023, milestone: "Built MVP in 6 weeks, got 5K users from TikTok" },
        { year: 2024, milestone: "Launched premium tier, 2K paying subscribers" },
        { year: 2025, milestone: "Expanded to English-speaking markets" },
      ],
      logoColor: "#ef4444",
    },
    {
      id: "ss_6",
      companyName: "CraftBox",
      founderName: "Sophie Dubois",
      ideaOrigin: "Curated local craft beer subscription",
      category: "Food & Beverage",
      location: "Paris, France",
      yearFounded: 2022,
      currentRevenue: "$420K ARR",
      employeeCount: 6,
      keyInsight: "The French craft beer scene was booming but had no discovery platform. We became the bridge between brewers and enthusiasts.",
      timeline: [
        { year: 2022, milestone: "Started with 10 local breweries, 200 subscribers" },
        { year: 2023, milestone: "Reached 2K subscribers, added tasting events" },
        { year: 2024, milestone: "Expanded to Lyon, Bordeaux, and Brussels" },
      ],
      logoColor: "#ec4899",
    },
    {
      id: "ss_7",
      companyName: "FixIt Pro",
      founderName: "Carlos Rivera",
      ideaOrigin: "On-demand handyman booking app",
      category: "Home Services",
      location: "São Paulo, Brazil",
      yearFounded: 2021,
      currentRevenue: "$1.1M ARR",
      employeeCount: 15,
      keyInsight: "Trust was the #1 barrier. Adding verified reviews and background checks tripled our conversion rate overnight.",
      timeline: [
        { year: 2021, milestone: "Launched with 50 vetted handymen in São Paulo" },
        { year: 2022, milestone: "Added plumbing, electrical, and painting services" },
        { year: 2023, milestone: "Expanded to Rio and Belo Horizonte" },
        { year: 2024, milestone: "10K+ completed jobs, 4.8 star average rating" },
      ],
      logoColor: "#06b6d4",
    },
    {
      id: "ss_8",
      companyName: "MindSpace",
      founderName: "Aisha Patel",
      ideaOrigin: "Mental health journaling app with AI insights",
      category: "Health & Medical",
      location: "Toronto, Canada",
      yearFounded: 2022,
      currentRevenue: "$780K ARR",
      employeeCount: 10,
      keyInsight: "We found that 'journaling for anxiety' had 18K monthly searches and the existing apps were all basic note-takers.",
      timeline: [
        { year: 2022, milestone: "MVP launched, featured on Product Hunt" },
        { year: 2023, milestone: "Added AI mood analysis, 15K daily active users" },
        { year: 2024, milestone: "Partnerships with 3 corporate wellness programs" },
      ],
      logoColor: "#8b5cf6",
    },
  ];
}
